# Permalinks
permalink: pretty

# Setup
title: Pup
description: Pup is a jekyll starter template intended for theme development. Pup comes packaged with base styles, plugins and examples of code making it the best thing ever.
url: ""
baseurl: ""

# Build settings
markdown: kramdown

# Uncomment for google analytics
# analytics_id: ""

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Dan Gold
  url: https://twitter.com/danielcgold.com
  email: me@danielcgold.com

# RSS
xml_limit: 20

# Custom vars
version: 0.0.1
github:
  repo: https://github.com/danielcgold/pup

# Plugins
gems:
  - jekyll-sitemap
